### ISSUE TITLE
mostVar uses MAD to get most variable genes

### ISSUE THREAD

**Issue by drisso** [epurdom/clusterExperiment#126]
Should add options to use MAD, variance, CV

**Comment by epurdom** [comment]
@drisso We need to add this in .transData. To be able to compare these in clusterMany, we need to have arguments for each one as well as their dimensions, i.e. we need that dimReduce take 'mostMAD', 'mostCV' in addition to existing 'mostVar' and 'PCA'; but would also need nPCAs, nVar, nCV, nMAD, which seems like a lot of parameters for clusterMany.

Alternatively, we could have in clusterMany one parameter nPCAs and another nMostFeatures (or something better -- any suggestions?) in clusterMany, so that for CV, MAD, and Var, you rotate through the same set of number of top features. (we can't do that for PCAs since it wouldn't make sense for them to be on the same scale). 

This would also apply to the function 'transform'

Also, should we change it from 'mostVar' to just 'Var', 'CV', 'MAD'?

**Comment by drisso** [comment]
I think it would be enough to keep one parameter to specify how many genes. I would also keep the name "nVar" as in number of most **variable** genes. The name would apply independently of whether they are selected by variance, mad, or CV. I find nMostFeatures not really self-explanatory.

Yes, I would call the three argument "Var", "CV", "MAD" (not sure about var vs Var). It would be more consistent with "PCA".

**Comment by epurdom** [comment]
'mostVar' has been changed to 'var' but otherwise, this is still waiting implementation until after the bioc release.

**Comment by epurdom** [comment]
'cv', 'mad', and 'var' are now all implemented in develop branch.
