### ISSUE TITLE
dendrogram doesn't resize when resizing heatmap

### ISSUE THREAD

**Issue by allonw** [epurdom/clusterExperiment#130]
When you draw a heatmap in a new window (e.g., in PC by adding the windows() command before one of the heatmaps command in the tutorial), the column dendrogram doesn't resize correctly.

`
# in the tutorial
# ......

windows()
out <- plotHeatmap(simData, sampleData=anno) 
`

**Comment by epurdom** [comment]
I think this is because under the hood, we are using the function aheatmap from the package NMF. It has a great deal of functionality, but it does have problems with resizing the plot of existing heatmaps. 

However, what you describe doesn't sound like resizing, but opening a new plot. I don't use PC, so I'm not familiar with the windows() command. What does this function do? Is it resizing an existing plot, or opening a new, fresh plotting window?

**Comment by allonw** [comment]
windows() is equivalent to quartz() on Mac and X11() on linux.

It opens a new plotting window in which the heatmap shows fine, but when I resize this window the dendrogram doesn't resize correctly

**Comment by epurdom** [comment]
Okay, then that sounds like the underlying problem of aheatmap, that I described above. Perhaps a request to them might trigger a solution or suggestion (https://github.com/renozao/NMF). It might also be an underlying problem from the grid package that they use for aheatmap, but they would know better than me.

**Comment by allonw** [comment]
Are you able to reproduce the problem? If so, perhaps could you notify them? You can provide much more useful information to them as the one using their interface (all I can say is "I'm calling a function that relies on your package and it has an issue").
