### ISSUE TITLE
plotCoClustering broken in develop

### ISSUE THREAD

**Issue by drisso** [epurdom/clusterExperiment#157]
The function plotCoClustering() produces a wrong heatmap, where the values on the diagonal blocks are lower than those outside.

I suspect that this is related to the change in the D matrix (that now is 1-D of the previous version?).

Hopefully, this affects only the plotting and not the actual clustering?

**Comment by drisso** [comment]
Note that plotCoClustering works fine after clusterMany.

What's broken, I think, is how clusterSingle() stores the coClustering matrix in the clusterExperiment object.

**Comment by epurdom** [comment]
@drisso This is if you run them 1 by 1, not after RSEC? You run
<pre>
cl<-combineMany(cl)
cl<-makeDendrogram(cl)
cl<-mergeClusters(cl)
</pre>
So you're saying that 
<pre>
cl<-combineMany(cl)
plotCoClustering(cl) #Broken
cl<-makeDendrogram(cl)
cl<-mergeClusters(cl)
plotCoClustering(cl) #Works
</pre>
Or something more complicated? Is the cl@coClustering slot the same in both steps? It's weird because nothing after combineMany should affect that slot...but then why different plots?

**Comment by drisso** [comment]
Sorry, that's not what I'm saying. `combineMany` works fine.

It's `clusterSingle` that is broken, i.e.,

```{r}
cl <- clusterSingle(se, subsample=TRUE, sequeintial=FALSE, ...)
plotCoClustering(cl) #broken
```
Let me know if you want a minimal working example.

**Comment by epurdom** [comment]
Ahh. Yes clusterSingle now returns the distance matrix (so 1-%co clustering). This is because we have other, default, distances if subsampling=FALSE, and I wanted the user to be able to access them (at the time I think I wanted to plot the distance matrix with the clustering information to see if the clustering was reasonable, using plotCoClustering; there's also an option 'returnD' to clusterSingle). 

However, since the slot is called 'coClustering' I recognize that is problematic. But I don't have a better idea for how to solve it... @drisso any thoughts? 

 I could set in a check in plotCoClustering so that if the clusterType=="clusterSingle" and clusterInfo information has subsample=TRUE, it plots 1-D. Does that sound good? Long-term, do we want something better?

**Comment by epurdom** [comment]
Okay, problem with that is that plotCoClustering doesn't know where @coClustering comes from. I'm thinking an argument "invert", which does 1-coClustering.

**Comment by epurdom** [comment]
And perhaps if diagonal is zero, invert=TRUE by default

**Comment by epurdom** [comment]
@drisso, I've pushed a change to develop that should implement the above. Let me know if it's still a problem.
