### ISSUE TITLE
eraseOld=TRUE throws error

### ISSUE THREAD

**Issue by drisso** [epurdom/clusterExperiment#163]
``` r
> cl <- mergeClusters(cl, mergeMethod="adjP", plot="none", cutoff=0.005,
                         eraseOld = TRUE)
Note: Merging will be done on ' combineMany ', with clustering index 2 
Error in validObject(.Object) : 
  invalid class “ClusterExperiment” object: dendro_clusters must have the same number of leaves as the number of (non-negative) clusters
```

Note that

``` r
> cl <- mergeClusters(cl, mergeMethod="adjP", plot="none", cutoff=0.005,
                         eraseOld = FALSE)
```

works

**Comment by drisso** [comment]
I suspect that this is related to #162 and that we should better check / remove dendrogram slots?

**Comment by epurdom** [comment]
@drisso do you need me to tackle this before the workshop?

**Comment by drisso** [comment]
Not really, thanks. I think this and #162 can wait for after the workshop. I just opened these to make sure not to forget.

**Comment by epurdom** [comment]
I've done some fixing of the removeClusters command and added unit tests. Previously, it was not updating the dendro_index slot when clusters were removed. This could have been the source of the problem, since it would be doing a check/comparison of the dendrogram with the wrong clustering. (There was already code to remove the dendrogram if removing the clustering that created the dendrogram). 

However, there could be more going on. @drisso: any chance you could you give me some lead up code to this so I can know what was being erased and try to check if this fixed the problem?
