### ISSUE TITLE
plotDendrogram doesn't work when makeDendrogram doesn't use PCA as dimReduce option

### ISSUE THREAD

**Issue by liampurvis** [epurdom/clusterExperiment#172]
Using a subset of the data from the vignette:

<pre>
> cE <- clusterMany(se, isCount = FALSE , dimReduce = c('PCA', 'var'), nPCADims = c(3, 5, 7), nVarDims = c(300, 500, 700), ks = c(4:13), clusterFunction = c('pam'))
> cE <- combineMany(cE , proportion = 0.5 , minSize = 5 )
> cE <- makeDendrogram(cE , dimReduce = 'PCA', ndims = 5) #Works only in this form, needs both
> plotDendrogram(cE) #works
> cE <- makeDendrogram(cE , dimReduce = 'mad', ignoreUnassignedVar = TRUE) 
> plotDendrogram(cE) #Error
Error in plot.window(...) : need finite 'xlim' values
</pre>

**Comment by epurdom** [comment]
The dendrogram was getting huge edge lengths with dimReduce='mad' which upset plotting for some reason. 

Fixed bug (in develop branch) by

<pre>    
if(max(phyloObj$edge.length)>1e6) phyloObj$edge.length<-phyloObj$edge.length/max(phyloObj$edge.length) #otherwise get error
</pre>

But not sure why this is a problem for plotting, nor why its happening. @drisso do you get this problem with makeDendrogram using 'mad' on the brain data

**Comment by drisso** [comment]
No. I never saw this error in the cortical data.
