### ISSUE TITLE
mergeClusters propDE if ‘x‘ is a ClusterExperiment

### ISSUE THREAD

**Issue by mbcole** [epurdom/clusterExperiment#178]
The documentation describes a `propDE` output when `mergeCusters()` operates on a matrix. Is this information embedded in `ClusterExperiment` outputs? If not, this addition could be useful when choosing thresholds for later/updated calls to `mergeCusters()`. For example, we could choose a new cutoff by defining and inspecting the upper tail of DE proportions.

**Comment by epurdom** [comment]
Sorry Michael to have not responded to this. The problem is that mergeClusters returns a ClusterExperiment object, which has a defined structure and it is not easy to 'add' information to it in S4. For this reason, I think we have to keep the option to return that information as a vector only available to the 'advanced user' who can use the matrix version. The plotting options, however, that go along with mergeClusters does give the user that information visually.
