### ISSUE TITLE
Probelm with colors

### ISSUE THREAD

**Issue by SaskiaFreytag** [epurdom/clusterExperiment#239]
I am applying clusterExperiment in its default settings (from the vignette) to a 10x single cell dataset with 925 cells. Unfortunately, while RSEC runs it seems to produce this error message at the very end.

 Error in .plotClustersInternal(clusters = c(1, 1, 2, 2, 3, 3, 4, 4, 2,  : 
  Must give colPalette (i.e. distinct colors to be assigned to clustres) longer than number of clusters. Largest number of distinct clusters in the clusterings:75. Length of colPalette:60
In addition: Warning messages:
1: In .makeColors(clusters, colors = bigPalette) :
  too many clusters to have unique color assignments
2: In .makeColors(clusters, colors = bigPalette) :
  too many clusters to have unique color assignments
3: In .makeColors(clusters, colors = bigPalette) :
  too many clusters to have unique color assignments
4: In .makeColors(clusters, colors = bigPalette) :
  too many clusters to have unique color assignments

**Comment by epurdom** [comment]
What version are you using of clusterExperiment? Because it should allow the number of distinct clusters up to 484 with the latest version, but this indicates only 60 are being used. 

Regardless, this is a poor performance to make this stop the program. So I will consider this a bug and change the code so that no single error after the clusterMany step will break RSEC.

**Comment by SaskiaFreytag** [comment]
I was using the 1.4.0 version on Bioconductor, I should have tried the github version before submitting a ticket. :) Thanks for checking this for me.

**Comment by epurdom** [comment]
I've just pushed a fix on the master branch and bioconductor (devel version) so that when RSEC hits an error, it will still return the results up until the point it hit an error. And that particular issue in mergeClusters now will not create an error, but rather a warning message (3941635b8eb30).

**Comment by epurdom** [comment]
What version are you using of clusterExperiment? Because it should allow the number of distinct clusters up to 484 with the latest version, but this indicates only 60 are being used. 

Regardless, this is a poor choice to make this stop the program. So I will consider this a bug and change the code so it doesn’t break RSEC.
