### ISSUE TITLE
What has changed about the output in the new version?

### ISSUE THREAD

**Issue by spholmes** [epurdom/clusterExperiment#240]
Elizabeth,

We are testing the compatibility of our book with Wolfgang and the new versions of the BioC
packages we use. The only remaining problem we seem to have is with clusterExperiment
output that throws an error.

The code we had:
```
library("clusterExperiment")
options(getClass.msg = FALSE)
library("scRNAseq")
data("fluidigm")
se = fluidigm[, fluidigm$Coverage_Type == "High"]
normCounts = round(limma::normalizeQuantiles(assay(se)))
assays(se) = list(normalized_counts = normCounts)
ce = clusterMany(se, clusterFunction = "pam", ks = 5:10, run = TRUE,
  isCount = TRUE, dimReduce = c("var"), nVarDims = c(60, 100, 150))
plotClusters(ce, whichClusters = "workflow", axisLine = -1)
```

and a plot with better `labels:`
```    
defaultMar<-par("mar")
plotCMar<-c(1.1,8.1,4.1,1.1)
par(mar=plotCMar)
namesClusters=names(clusterLegend(ce)[1:18])
nc=paste("Nfeat.",substring(namesClusters,13,21),sep="")
clusterLabels(ce)<-nc
plotClusters(ce, whichClusters = "workflow", axisLine = -1)
par(mar=defaultMar)
```

Now throws an error if instead of version 1.4 we use version 1.99.4,
the error says:
```
Error in 
clusterLabels<-(*tmp*, value = c("Nfeat.", "Nfeat.", "Nfeat.",  :
  value must be a vector of length equal to NCOL(clusterMatrix(object)):6
> clusterLabels(ce)
[1] "k=5"  "k=6"  "k=7"  "k=8"  "k=9"  "k=10"
> nc
 [1] "Nfeat."   "Nfeat."   "Nfeat."   "Nfeat."   "Nfeat."   "Nfeat."
 [7] "Nfeat.NA" "Nfeat.NA" "Nfeat.NA" "Nfeat.NA" "Nfeat.NA" "Nfeat.NA"
[13] "Nfeat.NA" "Nfeat.NA" "Nfeat.NA" "Nfeat.NA" "Nfeat.NA" "Nfeat.NA"
```
I believe this is due to a change in output from the function, is there someone I can
read about so that I can make the code run again?

Thanks
Susan

**Comment by spholmes** [comment]
Sorry to be a bother, I made a little more headway on this - testing various things.
I was actually able to make our code run if I only install the new version of clusterExperiment.
ie version ‘1.99.4’ and kept the older version of everything else.

So now I know the culprit is not clusterExperiment but something new it depends on.
I will continue and comment once I have found the exact package which is causing the glitch.

Thanks for all the hard work in doing this, very useful.
Susan

**Comment by epurdom** [comment]
Hi Susan,

The culprit **is** actually `clusterExperiment` -- sorry!

We did a major change for 2.0.0 (coming in the Bioc release tomorrow) to make it compatible with the new bioconductor class `SingleCellExperiment`. This class stores the results of a PCA or other dimensionality reduction so that they do not need to be continually recalculated. Previously we were recalculating them on the fly every time any function needed them which was clearly a poor idea with large data sets. We also took this opportunity to also save the filtering statistics that we create (e.g. filtering on variance, as in your example) in a colData object. This isn't the same degree of a time sink, but it is annoying. All of this is done under-the-hood when you call `clusterMany`. An advantage to this is that you can use any dimensionality reduction or filtering statistic in our methods if you calculate them yourself and save them in the right place (in the right slot in `SingleCellExperiment` or as a column in the `colData` class). 

As a result we changed argument names to match with `SingleCellExperiment` (and that our argument names like `nVarDims` were hold-overs from when we only did filtering on variance, which for a long time even before this change we've allowed other options). 

Here is a summary (from the NEWS):

> * MAJOR CHANGE TO DEFINITION OF CLASS: This version consists of a major update of how dimensionality reduction and filtering is done. The class has been updated to extend the new `SingleCellExperiment` class, which save the dimensionality reductions. Furthermore, calculating of per-gene statistics, which are usually used for filtering, are stored in `colData` of the object and can be easily accessed and used for repeated filtering without recalculating. This has created a massive change under-the-hood in functions that allow dimensionality reduction and filtering. Changes to function names are the following:
> 	- `transform` is now `transformData`
> 	- New functions `makeReducedDims` and `makeFilterStats` will calculate (and thus store) dimensionality reductions and statistics for filtering the data.
> 	- New function `filterData` will return the filtered data as a matrix
> 	- New functions `listBuiltInReducedDims` and `listBuiltInFilterStats` give the list of currently available functions for dimensionality reduction and filtering statistics, respectively.
> 	- Filtering on arbitrary statistics and user-defined dimensionality reduction can used in `clusterMany` and related functions, so long as they are saved in the appropriate slots of the object.
> * Changed the following functions/arguments to be consistent with SingleCellExperiment naming conventions and improve distinction between terminology of cluster and clustering.
> 	- Capitalized constructor functions. Now: `ClusterFunction()` and `ClusterExperiment()`
> 	- `nPCADims` now changed to `nReducedDims` in clusterMany-related functions
> 	- `nVarDims` now changed to `nFilterDims` in clusterMany-related functions
> 	- `dimReduce` argument now changed to `reduceMethod` across functions
> 	- `ndims` to `nDims` in `clusterSingle` and `makeDendrogram` to keep consistency.
> 	- `plotDimReduce` to `plotReducedDims`
> 	- Changed `nClusters` to `nClusterings` to better indicate purpose of function. `nClusters` now gives the number of clusters per clustering.
> 	- `addClusters` to `addClusterings` and `removeClusters` to `removeClusterings`. New function `removeClusters` allows the user to actually ``remove" a cluster or clusters from a clustering by assigning samples in those clusters to `-1` value.
> 	- `clusterInfo()` to `clusteringInfo()`


Going back to your code, you are getting caught by the fact that the argument names have changed. 
That code is not actually doing any filtering, so you are only clustering on different k values and so creating only 6 clusterings. 

```
> nClusterings(ce)
[1] 6
> clusterLabels(ce)
[1] "k=5"  "k=6"  "k=7"  "k=8"  "k=9"  "k=10"
```

If you change the code to have the new argument names, I think this fixes it:
```
ce2<-clusterMany(se, clusterFunction = "pam", ks = 5:10, run = TRUE,
  isCount = TRUE, reduceMethod = c("var"), nFilterDims = c(60, 100, 150))
```

```
> nClusterings(ce2)
[1] 18
> clusterLabels(ce2)
 [1] "nFilterDims=60,k=5"   "nFilterDims=100,k=5"  "nFilterDims=150,k=5"  "nFilterDims=60,k=6"   "nFilterDims=100,k=6" 
 [6] "nFilterDims=150,k=6"  "nFilterDims=60,k=7"   "nFilterDims=100,k=7"  "nFilterDims=150,k=7"  "nFilterDims=60,k=8"  
[11] "nFilterDims=100,k=8"  "nFilterDims=150,k=8"  "nFilterDims=60,k=9"   "nFilterDims=100,k=9"  "nFilterDims=150,k=9" 
[16] "nFilterDims=60,k=10"  "nFilterDims=100,k=10" "nFilterDims=150,k=10"
```

Sorry for the confusion that this created. Now that the new release of bioconductor is coming out, I will put together a summary of the changes ("New with 2.0.0") on the github repository. Glad you are finding the package useful!

All of the best,
Elizabeth
