### ISSUE TITLE
add sample names to clusterMatrix ?

### ISSUE THREAD

**Issue by rkchance** [epurdom/clusterExperiment#249]
Hi, Diya and I are working with the clusterMatrix slot, and have noticed that there are no row names.

Though we know that the samples are in the same order as the colnames(clusterExperiment object), we do have to add the row names manually every time we look at the clusterMatrix in isolation. 

Would it be possible to add a line of code to add these row names to the clusterMatrix?

**Comment by epurdom** [comment]
Hi Kelly,
You should use the clusterMatrix() function to extract the matrix (i.e. clusterMatrix(cc) rather than cc@clusterMatrix). Basically you should never need to use the @ for any of the slots, but use the accessor functions. (Indeed that’s my recommendation for most S4-based packages).
Elizabeth

**Comment by epurdom** [comment]
Sorry, I addressed my email to Kelly without looking at the sender, since I knew Kelly and Diya are working together as well.

**Comment by rkchance** [comment]
Thank you, Elizabeth.  Thinking the author was Kelly was a fair assumption,
I'd say!
We will use the accessor functions.
Best,
Rebecca
