### ISSUE TITLE
if statements on visualizeData argument of plotHeatmap when it is a matrix/data.frame 

### ISSUE THREAD

**Issue by drisso** [epurdom/clusterExperiment#55]
visualizeData can be either a character string or a matrix/data.frame. If the latter the statements
```
colorScale = if (visualizeData == "centerAndScaled") seqPal3 else seqPal5
```
and
```
clusterSamplesData<-if(visualizeData=="original") transObj$x else heatData
```
throw warnings.

This could be probably fixed by something like any(), but it's possibly a better solution to have two different arguments?

**Comment by epurdom** [comment]
I prefer one argument, myself, because it fits with how the other arguments work. I.e. you can have simple characters that give a default option, or provide explicit control. Otherwise the number of arguments expand greatly. I think a better solution is to not have the 
`colorScale = if (visualizeData == "centerAndScaled") seqPal3 else seqPal5`
in the arguments, and just do a more complicated catch if the colorScale argument is missing, e.g.
if(missing(colorScale)){
if(is.data.frame(visualizeData) | is.matrix(visualizeData) ...
else...
}
