### ISSUE TITLE
plotClusters test fails

### ISSUE THREAD

**Issue by drisso** [epurdom/clusterExperiment#77]
The following test fails. It is not clear to me why it shouldn't. If you reset the colors that shouldn't the object change?

```{r}
    plotClusters(ceSim,whichClusters=2)
    x5<-plotClusters(ceSim,whichClusters=2,resetColors=TRUE)
    expect_equal(x5,ceSim)
```

I've marked it as a priority because I'm hoping to make sure that all the current tests are passed as this will make the Travis CI build correctly and it will be easier to detect commits that break the package.

**Comment by epurdom** [comment]
I don’t see why they should be the same. If you resetColors=TRUE, then x5 no longer has to have the same colorLegend info as ceSim

I think that test used to work because there was no -1 before in the clustering. There’s some weird color choices in plotClusters when there is a -1 (because right now -1 is treated as a group and given a color, and only at the end after all the colors are set, is -1 given a white, so -1 clusters “suck up” colors in the color spectrum). I want to change this, but it requires major recoding of the internal plotClustering command, while doing at the end was an easy fix.

So just delete the expect_equal line. It wasn’t a good test anyway because it wasn’t testing something important.

**Comment by drisso** [comment]
Ok. I'll take care of this.

**Comment by drisso** [comment]
Removed the test
